import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { createTripDays } from '../data/tripDays'
import { prepareImage } from '../lib/images'
import { createVideoPoster, getMediaType, safeMediaExtension, validateMediaSize } from '../lib/media'
import { supabase, supabaseConfigurationError } from '../lib/supabase'
import type { Activity, AnimalType, Expense, Highlight, MediaType, Memory, PackingItem, ReefSighting, TripDay } from '../types'
import { DataContext } from './DataContext'
import { useAuth } from '../hooks/useAuth'
import type { FlightState, FlightUpdate } from '../features/flights/flightTypes'

interface DayRow { id:string; date:string; day_number:number; title:string|null; description:string|null; highlight:string|null; is_public:boolean }
interface ActivityRow { id:string; trip_day_id:string; title:string; description:string|null; start_time:string|null; location:string|null; category:string; is_public:boolean; created_at:string }
interface ReefRow { id:string; animal_type:AnimalType; species:string|null; sighting_date:string; sighting_time:string|null; location:string|null; count:number; notes:string|null; is_public:boolean; created_at:string }
interface MemoryRow { id:string; memory_date:string; title:string; description:string|null; location:string|null; image_url:string|null; media_type:MediaType|null; media_url:string|null; media_path:string|null; thumbnail_url:string|null; favorite:boolean; is_public:boolean; created_at:string }
interface HighlightRow { id:string; title:string; description:string|null; highlight_date:string|null; category:string; status:'planned'|'completed'; image_url:string|null; is_public:boolean; created_at:string }
interface PackingRow { id:string; title:string; category:string; packed:boolean }
interface ExpenseRow { id:string; expense_date:string; description:string; amount:number; currency:string; category:Expense['category'] }
interface FlightUpdateRow { id:string; flight_number:string; flight_date:string; status:FlightState; gate:string|null; estimated_departure:string|null; estimated_arrival:string|null; note:string|null; updated_at:string; updated_by:string|null }

interface QueryResult { error: { code?: string; message: string } | null; status?: number; statusText?: string }
function reportQueryErrors(results: Array<{ table: string; result: QueryResult }>) {
  const failed = results.filter(item => item.result.error)
  if (import.meta.env.DEV) failed.forEach(({ table, result }) => console.error('[Supabase data query]', { table, code: result.error?.code, status: result.status, statusText: result.statusText, message: result.error?.message }))
  return failed.map(item => item.table)
}
const mutationMessage = 'Die Änderung konnte nicht in Supabase gespeichert werden. Bitte versuche es erneut.'
const cleanupKey='honeymoon.storage-cleanup.v1'
const flightCacheKey='honeymoon.flight-updates.v1'
function queueStorageCleanup(path:string){try{const items=JSON.parse(localStorage.getItem(cleanupKey)||'[]')as string[];localStorage.setItem(cleanupKey,JSON.stringify(Array.from(new Set([...items,path]))))}catch{/* Cleanup wird beim nächsten Owner-Vorgang erneut versucht. */}}
async function retryStorageCleanup(){if(!supabase)return;try{const items=JSON.parse(localStorage.getItem(cleanupKey)||'[]')as string[];if(!items.length)return;const result=await supabase.storage.from('memories').remove(items);if(!result.error)localStorage.removeItem(cleanupKey)}catch{/* Netzwerkfehler: Queue bleibt erhalten. */}}
function mapFlightUpdates(rows:FlightUpdateRow[]):FlightUpdate[]{return rows.map(row=>({id:row.id,flightNumber:row.flight_number,flightDate:row.flight_date,status:row.status,gate:row.gate??undefined,estimatedDeparture:row.estimated_departure?.slice(0,5),estimatedArrival:row.estimated_arrival?.slice(0,5),note:row.note??undefined,updatedAt:row.updated_at,updatedBy:row.updated_by??undefined}))}
function mapExpenses(rows:ExpenseRow[]):Expense[]{return rows.map(e=>({id:e.id,date:e.expense_date,description:e.description,amount:Number(e.amount),currency:e.currency,category:e.category}))}
function cachedFlightUpdates():FlightUpdate[]{try{return JSON.parse(localStorage.getItem(flightCacheKey)||'[]')as FlightUpdate[]}catch{return[]}}
function cacheFlightUpdates(updates:FlightUpdate[]){try{localStorage.setItem(flightCacheKey,JSON.stringify(updates))}catch{/* Der Offline-Cache ist optional. */}}
export function DataProvider({children}:{children:ReactNode}) {
  const { owner, user, configured } = useAuth(); const [tripDays,setTripDays]=useState<TripDay[]>(createTripDays); const [sightings,setSightings]=useState<ReefSighting[]>([]); const [memories,setMemories]=useState<Memory[]>([]); const [highlights,setHighlights]=useState<Highlight[]>([]); const [packing,setPacking]=useState<PackingItem[]>([]); const [expenses,setExpenses]=useState<Expense[]>([]); const [flightUpdates,setFlightUpdates]=useState<FlightUpdate[]>(cachedFlightUpdates); const [flightUpdatesLoading,setFlightUpdatesLoading]=useState(configured); const [flightUpdatesStale,setFlightUpdatesStale]=useState(false); const [flightUpdatesError,setFlightUpdatesError]=useState<string|null>(null); const [loading,setLoading]=useState(configured); const [error,setError]=useState<string|null>(supabaseConfigurationError)
  const refreshExpenses=useCallback(async()=>{const client=supabase;if(!client||!owner)return;const result=await client.from('expenses').select('*').order('expense_date',{ascending:false});if(result.error){if(import.meta.env.DEV)console.warn('[Supabase expense refresh]',{code:result.error.code,status:result.status,message:result.error.message});return}setExpenses(mapExpenses(result.data as ExpenseRow[]))},[owner])
  const refreshFlights=useCallback(async()=>{const client=supabase;if(!client){setFlightUpdatesLoading(false);return}setFlightUpdatesLoading(true);const result=await client.from('flight_updates').select('*').order('flight_date');if(result.error){if(import.meta.env.DEV)console.warn('[Supabase flight updates]',{code:result.error.code,status:result.status,message:result.error.message});setFlightUpdatesStale(cachedFlightUpdates().length>0);setFlightUpdatesError('Manuelle Flugupdates konnten nicht geladen werden. Der feste Flugplan bleibt verfügbar.')}else{const updates=mapFlightUpdates(result.data as FlightUpdateRow[]);setFlightUpdates(updates);cacheFlightUpdates(updates);setFlightUpdatesStale(false);setFlightUpdatesError(null)}setFlightUpdatesLoading(false)},[])
  const refresh=useCallback(async()=>{
    const client=supabase; if(!client){setLoading(false);setFlightUpdatesLoading(false);return} setLoading(true);setError(null);const flightPromise=refreshFlights()
    const [daysResult,activitiesResult,reefResult,memoriesResult,highlightsResult] = await Promise.all([client.from('trip_days').select('*').order('date'),client.from('activities').select('*').order('start_time'),client.from('reef_sightings').select('*').order('sighting_date',{ascending:false}),client.from('memories').select('*').order('memory_date',{ascending:false}),client.from('highlights').select('*').order('highlight_date')])
    const publicFailures=reportQueryErrors([{table:'trip_days',result:daysResult},{table:'activities',result:activitiesResult},{table:'reef_sightings',result:reefResult},{table:'memories',result:memoriesResult},{table:'highlights',result:highlightsResult}])
    if(publicFailures.length){setError(`Supabase konnte folgende öffentliche Daten nicht laden: ${publicFailures.join(', ')}.`);setLoading(false);return}
    const acts=(activitiesResult.data as ActivityRow[]).map(a=>({id:a.id,tripDayId:a.trip_day_id,title:a.title,description:a.description??undefined,startTime:a.start_time??undefined,location:a.location??undefined,category:a.category,public:true,createdAt:a.created_at}))
    const rows=daysResult.data as DayRow[]; setTripDays(rows.length?rows.map(d=>({id:d.id,date:d.date,dayNumber:d.day_number,title:d.title||`Reisetag ${d.day_number}`,description:d.description||'',highlight:d.highlight??undefined,public:d.is_public,activities:acts.filter(a=>a.tripDayId===d.id)})):createTripDays())
    setSightings((reefResult.data as ReefRow[]).map(s=>({id:s.id,animalType:s.animal_type,species:s.species??undefined,date:s.sighting_date,time:s.sighting_time?.slice(0,5),location:s.location??undefined,count:s.count,notes:s.notes??undefined,public:true,createdAt:s.created_at})))
    const memoryRows=memoriesResult.data as MemoryRow[]
    const signed=await Promise.all(memoryRows.map(async m=>{const mediaPath=m.media_path||m.media_url||m.image_url||undefined;const thumbnailPath=m.thumbnail_url||undefined;const [media,thumbnail]=await Promise.all([mediaPath?client.storage.from('memories').createSignedUrl(mediaPath,3600):undefined,thumbnailPath?client.storage.from('memories').createSignedUrl(thumbnailPath,3600):undefined]);return{mediaPath,thumbnailPath,media:media?.data?.signedUrl,thumbnail:thumbnail?.data?.signedUrl}}))
    setMemories(memoryRows.map((m,i)=>({id:m.id,date:m.memory_date,title:m.title,description:m.description??undefined,location:m.location??undefined,mediaType:m.media_type||'image',media:signed[i].media,mediaPath:signed[i].mediaPath,thumbnail:signed[i].thumbnail,thumbnailPath:signed[i].thumbnailPath,image:(m.media_type||'image')==='image'?signed[i].media:undefined,imagePath:m.image_url??undefined,favorite:m.favorite,public:true,createdAt:m.created_at})))
    setHighlights((highlightsResult.data as HighlightRow[]).map(h=>({id:h.id,title:h.title,description:h.description??undefined,date:h.highlight_date??undefined,category:h.category,status:h.status,image:h.image_url??undefined,public:true,createdAt:h.created_at})))
    if(owner){const [packResult,expenseResult]=await Promise.all([client.from('packing_items').select('*').order('created_at'),client.from('expenses').select('*').order('expense_date',{ascending:false})]);const privateFailures=reportQueryErrors([{table:'packing_items',result:packResult},{table:'expenses',result:expenseResult}]);if(privateFailures.length)setError(`Owner-Login erfolgreich, aber private Daten konnten nicht geladen werden: ${privateFailures.join(', ')}.`);if(!packResult.error)setPacking((packResult.data as PackingRow[]).map(p=>({id:p.id,label:p.title,category:p.category,packed:p.packed})));if(!expenseResult.error)setExpenses(mapExpenses(expenseResult.data as ExpenseRow[]));await retryStorageCleanup()}else{setPacking([]);setExpenses([])}
    await flightPromise;setLoading(false)
  },[owner,refreshFlights])
  useEffect(()=>{void Promise.resolve().then(refresh)},[refresh])
  useEffect(()=>{const client=supabase;if(!client)return;const channel=client.channel('public-flight-updates').on('postgres_changes',{event:'*',schema:'public',table:'flight_updates'},()=>void refreshFlights()).subscribe();return()=>{void client.removeChannel(channel)}},[refreshFlights])
  useEffect(()=>{const client=supabase;if(!client||!owner)return;const channel=client.channel(`owner-expenses-${user?.id??'current'}`).on('postgres_changes',{event:'*',schema:'public',table:'expenses'},()=>void refreshExpenses()).subscribe();return()=>{void client.removeChannel(channel)}},[owner,user?.id,refreshExpenses])
  const guard=()=>{if(!navigator.onLine)throw new Error('Du bist gerade offline. Änderungen können erst wieder gespeichert werden, sobald eine Verbindung besteht.');if(!supabase||!owner)throw new Error('Diese Aktion ist nur im Bearbeitungsmodus verfügbar.')}
  const run=async(action:()=>PromiseLike<{error:{message:string;code?:string}|null}>)=>{guard();const {error}=await action();if(error){if(import.meta.env.DEV)console.error('[Supabase mutation]',{code:error.code,message:error.message});throw new Error(mutationMessage)}await refresh()}
  const saveSighting=async(v:Omit<ReefSighting,'id'>&{id?:string})=>run(()=>supabase!.from('reef_sightings').upsert({id:v.id,animal_type:v.animalType,species:v.species||null,sighting_date:v.date,sighting_time:v.time||null,location:v.location||null,count:v.count,notes:v.notes||null,is_public:true},{onConflict:'id'}))
  const deleteSighting=async(id:string)=>run(()=>supabase!.from('reef_sightings').delete().eq('id',id))
  const saveMemory=async(v:Omit<Memory,'id'|'media'|'thumbnail'|'image'>&{id?:string},file?:File,onProgress?:(progress:number)=>void)=>{guard();const oldMediaPath=v.mediaPath||v.imagePath;const oldThumbnailPath=v.thumbnailPath;let newMediaPath:string|undefined;let newThumbnailPath:string|undefined;let mediaType=v.mediaType||'image';onProgress?.(5);if(file){mediaType=getMediaType(file);validateMediaSize(file,mediaType);onProgress?.(12);const payload=mediaType==='image'?await prepareImage(file):file;const extension=mediaType==='image'&&payload.type==='image/webp'?'webp':safeMediaExtension(file,mediaType);const inferredType:Record<string,string>={jpg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif',mp4:'video/mp4',mov:'video/quicktime',webm:'video/webm'};const contentType=payload.type||file.type||inferredType[extension];const year=v.date.slice(0,4)||new Date().getFullYear().toString();newMediaPath=`${user!.id}/${year}/${crypto.randomUUID()}.${extension}`;onProgress?.(25);const upload=await supabase!.storage.from('memories').upload(newMediaPath,payload,{contentType,upsert:false});if(upload.error)throw new Error(mediaType==='video'?'Das Video konnte nicht hochgeladen werden. Bitte prüfe deine Verbindung.':'Das Foto konnte nicht hochgeladen werden. Bitte prüfe deine Verbindung.');onProgress?.(78);if(mediaType==='video'){const poster=await createVideoPoster(file);if(poster){newThumbnailPath=`${user!.id}/${year}/${crypto.randomUUID()}.webp`;const posterUpload=await supabase!.storage.from('memories').upload(newThumbnailPath,poster,{contentType:'image/webp',upsert:false});if(posterUpload.error)newThumbnailPath=undefined}}}const mediaPath=newMediaPath||oldMediaPath||null;const thumbnailPath=newMediaPath?(newThumbnailPath||null):(oldThumbnailPath||null);onProgress?.(88);const {error}=await supabase!.from('memories').upsert({id:v.id,memory_date:v.date,title:v.title,description:v.description||null,location:v.location||null,media_type:mediaType,media_url:mediaPath,media_path:mediaPath,thumbnail_url:thumbnailPath,image_url:mediaType==='image'?mediaPath:null,favorite:v.favorite,is_public:true},{onConflict:'id'});if(error){const uploaded=[newMediaPath,newThumbnailPath].filter(Boolean)as string[];if(uploaded.length)await supabase!.storage.from('memories').remove(uploaded);if(import.meta.env.DEV)console.error('[Memory save]',{code:error.code,message:error.message});throw new Error('Die Erinnerung konnte nicht gespeichert werden. Ist die v0.4-Migration bereits ausgeführt?')}const stale=[oldMediaPath,oldThumbnailPath].filter((path):path is string=>Boolean(path)&&path!==newMediaPath&&path!==newThumbnailPath);if(newMediaPath&&stale.length){const cleanup=await supabase!.storage.from('memories').remove(stale);if(cleanup.error){stale.forEach(queueStorageCleanup);await refresh();throw new Error('Erinnerung gespeichert. Alte Mediendateien werden beim nächsten Online-Aufruf erneut bereinigt.')}}onProgress?.(100);await refresh()}
  const deleteMemory=async(id:string)=>{guard();const memory=memories.find(m=>m.id===id);const paths=Array.from(new Set([memory?.mediaPath||memory?.imagePath,memory?.thumbnailPath].filter(Boolean)as string[]));const {error}=await supabase!.from('memories').delete().eq('id',id);if(error)throw new Error('Die Erinnerung konnte nicht gelöscht werden.');if(paths.length){const removed=await supabase!.storage.from('memories').remove(paths);if(removed.error){paths.forEach(queueStorageCleanup);await refresh();throw new Error('Erinnerung gelöscht. Die Mediendateien werden beim nächsten Online-Aufruf erneut bereinigt.')}}await refresh()}
  const saveTripDay=async(v:TripDay)=>run(()=>supabase!.from('trip_days').update({title:v.title,description:v.description,highlight:v.highlight||null,is_public:true}).eq('id',v.id))
  const saveActivity=async(v:Omit<Activity,'id'>)=>run(()=>supabase!.from('activities').insert({trip_day_id:v.tripDayId,title:v.title,description:v.description||null,start_time:v.startTime||null,location:v.location||null,category:v.category,is_public:true}))
  const saveHighlight=async(v:Omit<Highlight,'id'>)=>run(()=>supabase!.from('highlights').insert({title:v.title,description:v.description||null,highlight_date:v.date||null,category:v.category,status:v.status,image_url:v.image||null,is_public:true}))
  const deleteHighlight=async(id:string)=>run(()=>supabase!.from('highlights').delete().eq('id',id))
  const savePacking=async(v:Omit<PackingItem,'id'>&{id?:string})=>run(()=>supabase!.from('packing_items').upsert({id:v.id,title:v.label,category:v.category,packed:v.packed},{onConflict:'id'}))
  const deletePacking=async(id:string)=>run(()=>supabase!.from('packing_items').delete().eq('id',id))
  const saveExpense=async(v:Omit<Expense,'id'>)=>run(()=>supabase!.from('expenses').insert({expense_date:v.date,description:v.description,amount:v.amount,currency:v.currency,category:v.category}))
  const deleteExpense=async(id:string)=>run(()=>supabase!.from('expenses').delete().eq('id',id))
  const saveFlightUpdate=async(v:FlightUpdate)=>{guard();const{error}=await supabase!.from('flight_updates').upsert({flight_number:v.flightNumber,flight_date:v.flightDate,status:v.status,gate:v.gate||null,estimated_departure:v.estimatedDeparture||null,estimated_arrival:v.estimatedArrival||null,note:v.note||null,updated_by:user!.id},{onConflict:'flight_number,flight_date'});if(error){if(import.meta.env.DEV)console.error('[Flight update mutation]',{code:error.code,message:error.message});throw new Error('Der Flugstatus konnte nicht gespeichert werden. Bitte prüfe Verbindung und v0.5-Migration.')}await refreshFlights()}
  const value={tripDays,sightings,memories,highlights,packing,expenses,flightUpdates,flightUpdatesLoading,flightUpdatesStale,flightUpdatesError,loading,error,refresh,saveFlightUpdate,saveSighting,deleteSighting,saveMemory,deleteMemory,saveTripDay,saveActivity,saveHighlight,deleteHighlight,savePacking,deletePacking,saveExpense,deleteExpense}
  return <DataContext.Provider value={value}>{children}</DataContext.Provider>
}
