import { ArrowRight, CalendarDays, MapPin, Sparkles, Waves } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Section } from '../components/Section'
import { tripConfig } from '../config/trip'
import { formatDate } from '../data/tripDays'
import { ShareButton } from '../features/share/ShareButton'
import { Stats } from '../features/stats/Stats'
import { WeatherCard } from '../features/weather/WeatherCard'
import { useData } from '../hooks/useData'
import { getTripPhase } from '../hooks/useTripPhase'

interface FeedItem { id:string; kind:string; icon:string; title:string; text:string; createdAt:string; to:string }
function resortDate(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:tripConfig.weatherLocation.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=(type:string)=>parts.find(p=>p.type===type)?.value;return `${part('year')}-${part('month')}-${part('day')}`}

export function HomePage(){
  const phase=getTripPhase();const{sightings,memories,highlights,tripDays,loading}=useData();const activities=tripDays.flatMap(day=>day.activities);const currentDate=resortDate();const currentDay=tripDays.find(day=>day.date===currentDate);const count=(type:string)=>sightings.filter(s=>s.animalType===type).reduce((a,b)=>a+b.count,0)
  const feed:FeedItem[]=[...memories.map(m=>({id:`m-${m.id}`,kind:'NEUE ERINNERUNG',icon:'📸',title:m.title,text:m.location||formatDate(m.date),createdAt:m.createdAt||m.date,to:'/memories'})),...sightings.map(s=>({id:`s-${s.id}`,kind:'NEUE RIFF-BEGEGNUNG',icon:s.animalType==='Hai'?'🦈':'🐠',title:`${s.count} ${s.species||s.animalType}`,text:s.location||formatDate(s.date),createdAt:s.createdAt||s.date,to:'/reef'})),...highlights.map(h=>({id:`h-${h.id}`,kind:'NEUES HIGHLIGHT',icon:'✨',title:h.title,text:h.description||h.category,createdAt:h.createdAt||h.date||'',to:'/more'})),...activities.map(a=>({id:`a-${a.id}`,kind:'NEUE AKTIVITÄT',icon:'🌴',title:a.title,text:a.location||a.description||'Unser Reiseplan',createdAt:a.createdAt||'',to:'/trip'}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5)
  const todayMemories=memories.filter(m=>m.date===currentDate);const todaySightings=sightings.filter(s=>s.date===currentDate);const todayHighlights=highlights.filter(h=>h.date===currentDate)
  return <><section className="hero"><img src="/images/maldives-hero.png" alt="Wasservilla in einer türkisfarbenen Lagune auf den Malediven bei Sonnenaufgang" fetchPriority="high"/><div className="hero-shade"/><div className="hero-top"><span>{tripConfig.travelers}</span><ShareButton compact/></div><div className="hero-content"><p className="eyebrow light">{phase.eyebrow}</p><h1>{phase.headline}</h1><p className="hero-detail">{phase.detail}</p><div className="hero-place"><MapPin size={17}/><span><strong>{tripConfig.departureAirport} → Malediven</strong>{tripConfig.resort}</span></div></div><div className="scroll-cue"><span>ENTDECKEN</span><i/></div></section><div className="page-content home-content"><div className="intro"><p className="script">Unser kleines Stück Paradies</p><h2>Kommt mit auf unsere Reise.</h2><p>Von Hamburg bis zum türkisfarbenen Horizont – hier teilen wir unsere Flitterwochen mit Familie und Freunden.</p></div>
  {loading?<div className="skeleton-grid"><i/><i/><i/></div>:<div className="feature-grid"><article className="feature-card today-card"><div className="card-icon"><CalendarDays/></div><p className="eyebrow">{currentDay?`TAG ${currentDay.dayNumber} UNSERER HOCHZEITSREISE`:'BALD GEHT ES LOS'}</p><h3>{currentDay?currentDay.title:'Unsere Reise beginnt am 30. August'}</h3><p>{currentDay?(currentDay.description||'Unser heutiger Reisetag auf den Malediven.'):'Am 30. August um 15:30 Uhr startet unsere Hochzeitsreise ab Hamburg.'}</p><Link to="/trip">Reise ansehen <ArrowRight size={16}/></Link></article><WeatherCard/><article className="feature-card highlight-card"><Sparkles size={24}/><p className="eyebrow">BESONDERE MOMENTE</p>{highlights[0]?<><h3>{highlights[0].title}</h3><p>{highlights[0].description}</p></>:<><h3>Noch keine Highlights</h3><p>Hier teilen wir später unsere besonderen Erlebnisse.</p></>}</article><article className="feature-card reef-mini"><div><p className="eyebrow">BEGEGNUNGEN AM RIFF</p><h3>Leben unter der Wasseroberfläche</h3></div><div className="animal-counts"><span>◢ <b>{count('Hai')}</b><small>Haie</small></span><span>◯ <b>{count('Schildkröte')}</b><small>Schildkröten</small></span><span>◌ <b>{sightings.reduce((a,b)=>a+b.count,0)}</b><small>Tiere</small></span></div><Link to="/reef">Riff entdecken <ArrowRight size={16}/></Link></article></div>}
  {currentDay&&<Section eyebrow={`${formatDate(currentDay.date,{day:'numeric',month:'long'}).toUpperCase()} · TAG ${currentDay.dayNumber}`} title="Heute bei uns"><div className="today-journal">{currentDay.activities.map(a=><article key={a.id}><span>🌴</span><div><small>AKTIVITÄT</small><h3>{a.title}</h3><p>{a.startTime?.slice(0,5)} {a.location}</p></div></article>)}{todayMemories.map(m=><article key={m.id}><span>📸</span><div><small>ERINNERUNG</small><h3>{m.title}</h3><p>{m.location}</p></div></article>)}{todaySightings.map(s=><article key={s.id}><span>🐠</span><div><small>RIFF</small><h3>{s.count} {s.species||s.animalType}</h3><p>{s.location}</p></div></article>)}{todayHighlights.map(h=><article key={h.id}><span>✨</span><div><small>HIGHLIGHT</small><h3>{h.title}</h3></div></article>)}{!currentDay.activities.length&&!todayMemories.length&&!todaySightings.length&&!todayHighlights.length&&<div className="empty"><h3>Dieser Reisetag wartet auf seine Geschichte.</h3></div>}</div></Section>}
  <Section eyebrow="GERADE PASSIERT" title="Neu bei uns" action={<Link className="text-link" to="/memories">Alle Erinnerungen ansehen <ArrowRight size={15}/></Link>}>{feed.length?<div className="activity-feed">{feed.map(item=><Link key={item.id} to={item.to}><span>{item.icon}</span><div><small>{item.kind}</small><h3>{item.title}</h3><p>{item.text}</p></div><ArrowRight/></Link>)}</div>:<div className="empty"><Sparkles/><h3>Unsere Geschichte beginnt bald.</h3><p>Neue Erlebnisse erscheinen automatisch an dieser Stelle.</p></div>}</Section>
  <Section eyebrow="UNSERE GESCHICHTE" title="Neueste Erinnerungen" action={<Link className="text-link" to="/memories">Alle ansehen <ArrowRight size={15}/></Link>}>{memories.length?<div className="memory-strip">{memories.slice(0,3).map((m,i)=><Link to="/memories" className={`memory-tile tile-${i}`} key={m.id}><div className="memory-art">{m.image?<img src={m.image} alt=""/>:<span>≈</span>}</div><p>{formatDate(m.date)} · {m.location}</p><h3>{m.title}</h3></Link>)}</div>:<div className="empty"><h3>Hier entstehen bald unsere Erinnerungen.</h3><p>Die ersten Bilder und Geschichten folgen während der Reise.</p></div>}</Section><Section eyebrow={phase.phase==='after'?'UNSERE FLITTERWOCHEN 2026':'UNSERE REISE IN ZAHLEN'} title={phase.phase==='after'?'Erinnerungen für immer':'Kleine Momente, große Erinnerungen'}><Stats sightings={sightings} memories={memories} highlights={highlights.length}/></Section><section className="share-panel"><Waves/><div><p className="eyebrow">MITVERFOLGEN</p><h2>Unsere Reise teilen</h2><p>Schicke Familie und Freunden ein kleines Stück Paradies.</p></div><ShareButton/></section></div></>
}
