import { ArrowLeft, Clock3, CloudRain, CloudSun, Compass, Droplets, Eye, Gauge, RefreshCw, Sunrise, Sunset, Waves, Wind } from 'lucide-react'
import { Link } from 'react-router-dom'
import { tripConfig } from '../config/trip'
import { formatDate } from '../data/tripDays'
import { useResortTime } from '../features/weather/useResortTime'
import { compassDirection, weatherPresentation } from '../features/weather/weatherCodes'
import { useWeather } from '../features/weather/useWeather'

const time=(value:string)=>value.split('T')[1]?.slice(0,5)??'–'

export function WeatherPage(){
  const{data,loading,error,stale,refresh}=useWeather();const{time:resortTime,date:resortDate,greeting}=useResortTime();const today=data?.daily[0];const arrival=data?.daily.find(day=>day.date===tripConfig.startDate)
  return <div className="page-content page-top weather-page">
    <Link className="back-link" to="/"><ArrowLeft/> Zurück zur Startseite</Link>
    <header className="page-hero"><p className="eyebrow">SUN SIYAM IRU VELI</p><h1>Inselwetter</h1><p>Aktuelle Bedingungen und Vorhersagen für unser kleines Stück im Indischen Ozean.</p></header>
    <section className="resort-time-banner"><Clock3/><div><p className="eyebrow">IRU VELI · ORTSZEIT</p><strong>{resortDate} · {resortTime} Uhr Ortszeit</strong><span>{greeting}</span></div></section>
    {loading&&!data?<div className="weather-detail-skeleton"><i/><i/><i/></div>:data?<>
      <section className="weather-now"><div className="weather-main"><span>{weatherPresentation(data.current.weatherCode).icon}</span><div><p className="eyebrow">JETZT AUF IRU VELI</p><h2>{Math.round(data.current.temperature)} °C</h2><h3>{weatherPresentation(data.current.weatherCode).label}</h3><p>{Math.round(data.current.apparentTemperature)} °C gefühlt</p></div></div><div className="condition-grid"><div><Droplets/><strong>{data.current.humidity} %</strong><span>Luftfeuchtigkeit</span></div><div><Wind/><strong>{Math.round(data.current.windSpeed)} km/h</strong><span>Wind {compassDirection(data.current.windDirection)}</span></div><div><Eye/><strong>{data.current.cloudCover} %</strong><span>Bewölkung</span></div><div><CloudRain/><strong>{data.current.precipitation.toFixed(1)} mm</strong><span>Niederschlag</span></div></div></section>
      {arrival&&arrival.date!==today?.date&&<section className="arrival-forecast"><CloudSun/><div><p className="eyebrow">ERSTE VORHERSAGE FÜR UNSERE ANREISE</p><h3>{formatDate(arrival.date)} · {weatherPresentation(arrival.weatherCode).label}</h3><p>Voraussichtlich {Math.round(arrival.max)} °C / {Math.round(arrival.min)} °C und {arrival.rainProbability} % Regenwahrscheinlichkeit. Prognosen können sich ändern.</p></div></section>}
      <section className="today-weather"><header><div><p className="eyebrow">HEUTE AUF IRU VELI</p><h2>{today&&formatDate(today.date)}</h2></div></header><div className="condition-grid">{today&&<><div><Gauge/><strong>{Math.round(today.max)}° / {Math.round(today.min)}°</strong><span>Maximum / Minimum</span></div><div><CloudRain/><strong>{today.rainProbability} %</strong><span>Regenwahrscheinlichkeit</span></div><div><span className="uv-symbol">UV</span><strong>{Math.round(today.uvIndex)}</strong><span>UV-Index maximal</span></div><div><Wind/><strong>{Math.round(today.maxWind)} km/h</strong><span>Wind maximal</span></div><div><Sunrise/><strong>{time(today.sunrise)} Uhr</strong><span>Sonnenaufgang · Ortszeit</span></div><div><Sunset/><strong>{time(today.sunset)} Uhr</strong><span>Sonnenuntergang · Ortszeit</span></div></>}</div></section>
      <section className="forecast-section"><p className="eyebrow">DIE NÄCHSTEN TAGE</p><div className="forecast-row">{data.daily.slice(0,7).map(day=><article key={day.date}><span>{weatherPresentation(day.weatherCode).icon}</span><h3>{new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(new Date(`${day.date}T12:00`))}</h3><p>{Math.round(day.max)}° <small>{Math.round(day.min)}°</small></p><b><CloudRain/> {day.rainProbability} %</b></article>)}</div></section>
      <section className="sea-today"><div><p className="eyebrow">MEER HEUTE</p><h2>Bedingungen rund um die Insel</h2></div>{data.marine?<div className="condition-grid"><div><span className="sea-icon">≈</span><strong>{data.marine.seaTemperature.toFixed(1)} °C</strong><span>Wassertemperatur</span></div><div><Waves/><strong>{data.marine.waveHeight.toFixed(1)} m</strong><span>Wellen aus {compassDirection(data.marine.waveDirection)}</span></div><div><Compass/><strong>{data.marine.currentVelocity.toFixed(1)} km/h</strong><span>Strömung nach {compassDirection(data.marine.currentDirection)}</span></div></div>:<p>Meeresdaten gerade nicht verfügbar.</p>}<small>Informative Modelldaten. Keine Sicherheits-, Navigations- oder Tauchfreigabe.</small></section>
      <footer className="weather-updated">Zuletzt aktualisiert: {new Intl.DateTimeFormat('de-DE',{dateStyle:'short',timeStyle:'short'}).format(new Date(data.updatedAt))}{stale?' · letzter gespeicherter Stand':''}<button onClick={()=>void refresh(true)}><RefreshCw/> Aktualisieren</button></footer>
    </>:<div className="weather-error"><CloudSun/><h2>{error||'Wetterdaten gerade nicht verfügbar'}</h2><p>Die Ortszeit, Reise-App und alle Erinnerungen funktionieren unabhängig davon weiter.</p><button className="button owner-primary" onClick={()=>void refresh(true)}>Erneut versuchen</button></div>}
  </div>
}
